version: 2

updates:
    - package-ecosystem: "sbt"
      directory: "/"
      schedule:
          interval: "weekly"

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
