# Run acceptance tests on develop commits to check if ready for a release to main.
# Initiate release if all ok.
#
name: Acceptance Cycle

on:
  push:
    branches:
      - develop

jobs:
  acceptance:
    runs-on: ubuntu-latest

    steps:
      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Checkout
        uses: actions/checkout@v3

      - name: JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "sbt"

      - name: Compile
        run: sbt clean compile

      - name: License Header Check
        run: sbt headerCheck

      - name: Test
        run: sbt coverage test

      - name: Coverage Report
        id: c1
        run: |
          sbt coverageReport
          echo "c2=$(42)" >> $GITHUB_OUTPUT
#          echo '::set-output name=c2::$(xmllint --xpath "(/scoverage/@statement-rate + /scoverage/@branch-rate) div 2" target/scala-3.2.1/scoverage-report/scoverage.xml)'

      - name: Coverage Check
        run: |
          echo "${{ steps.c1.outputs.C2 }}"
          if [ "${{ steps.c1.outputs.C2 }}" < 75 ]
            echo "failed"
          else if [ "${{ steps.c1.outputs.C2 }}" < 90 ]
            echo "warning"
          else
            echo "passed"
          fi

      - name: Publish Check
        run: |
          sbt publishLocal
          sbt publishM2
