# Run acceptance tests on develop commits to check if ready for a release to main.
# Initiate release if all ok.
#
name: Acceptance Cycle

on:
  push:
    branches:
      - develop

jobs:
  acceptance:
    runs-on: ubuntu-latest

    steps:
      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Checkout
        uses: actions/checkout@v3

      - name: JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "sbt"

      - name: Compile
        run: sbt clean compile

      - name: License Header Check
        run: sbt headerCheck

      - name: Test
        run: sbt coverage test

      #          export COVERAGE=$(xmllint --xpath "(/scoverage/@statement-rate + /scoverage/@branch-rate) div 2" target/scala-3.2.1/scoverage-report/scoverage.xml)
      - name: Coverage Report
        id: c1
        run: |
          sbt coverageReport
          export COVERAGE=$(42)
          echo $COVERAGE
          if [ $COVERAGE < 75 ];
          then
            echo "::error Insufficient coverage; required 75% or more, got $COVERAGE"
          elif [ $COVERAGE < 90 ];
          then
            echo "::warning Insufficient coverage; required 75%, preferred 90% or more, got $COVERAGE"
          fi

      - name: Publish Check
        run: |
          sbt publishLocal
          sbt publishM2
