# Quick feedback for unit tests on non-main commits.
#
name: Commit Cycle

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Tooling
              run: |
                rustup update
                rustup component add clippy 

            - name: Compile
              run: cargo build

            - name: Lint
              run: cargo clippy

            - name: Test
              run: cargo test
