# Run publish-cycle on main commits.
#
# Publish cycle comprises:
# - publish site, coverage reports and API documentation to https://nigeleke.github.io
#
name: Publish Cycle

on:
  workflow_run:
    workflows: ["Acceptance Cycle"]
    branches: [develop]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "sbt"

      - name: Build
        run: |
          sbt clean headerCheck coverage test coverageReport doc
          mkdir docs0
          mkdir docs0/api
          mkdir docs0/coverage
          cp README.md docs0/
          VERSION=$(sbt -Dsbt.log.noformat=true "show scalaVersion" | grep -oP '(?<=\[info\] )\d+\.\d+\.\d+')
          cp -R target/scala-$VERSION/api/* docs0/api
          cp -R target/scala-$VERSION/scoverage-report/* docs0/coverage

      - name: Publish to Codecov
        uses: codecov/codecov-action@v3

      - name: Publish
        run: |
          git config --global user.email "nigeleke@users.noreply.github.com"
          git config --global user.name "Nigel Eke"
          export VERSION=$(git describe --abbrev=0 --tags)
          git checkout gh-pages
          rm -rf docs
          mv docs0 docs
          git add .
          git commit -m "Release $VERSION"
          git push