# Publish site, coverage reports and API documentation to https://nigeleke.github.io
# from latest main commit.
#
name: Publish Cycle

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "sbt"

      - name: Build
        run: sbt clean coverage headerCheck test coverageReport doc

      - name: Publish Site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .

      - name: Publish Coverage
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/scala-3.2.1/scoverage-report
          target-folder: coverage
          clean: false

# @Todo: Add this and publish when https://github.com/lampepfl/dotty/issues/16290 resolved.
#      - name: Publish API
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          folder: target/api
#          target-folder: coverage
#          clean: false
