name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      repository-projects: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'

    - name: Test
      run: sbt clean coverage test

    - name: Coverage
      run: sbt coverageReport

    - name: Publish Coverage
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
      with:
        dir: target/scala-3.2.0/scoverage-report
        branch: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Scaladoc
      run: sbt doc
